if (!selecting) selectword;
$word = gettext(seltopx, seltopy, selendx, selendy, 1);

$unicode_word = "";

#length = strlen($word);
#i = 0;
while (#i < #length) {
	#code = unicode(midstr($word, #i, #length - #i));

	$hex_uni = "+";
	$hex_uni = $hex_uni + hex(#code);

	$unicode_word = $unicode_word + $hex_uni;

	if (#code >  0xFF) #i = #i + 1;
	#i = #i + 1;
}

run "C:\\Program Files (x86)\\Logophile\\Logophile.exe -g -f -u"+$unicode_word;



