$key29 = "国際特許分類";
$key30 = "補充欄参照";
$key31 = "補充欄";

//各国際出願番号順に、各文書毎に、IPC番号のリストを作成
call GrepIPCs $key29;

//IPC番号の記載が、補充欄参照の場合、補充欄からIPC番号を取得する
call GrepOtherIPCs;

endmacro;

//各国際出願番号順に、各文書毎に、IPC番号のリストを作成
GrepIPCs:
	grep $$1, "*.txt", ".", regular, fullpath;

	//クリップボード履歴を念のため削除
	clearcliphist;
	//grepファイルの内容をコピー
	selectall;
	copy;

	beginclipboardread;
	#i=0;
	$a[#i]=getclipboard;

	$filename="";

	#k = 0;
	//クリップボードから各ファイルパスを読み込む。
	while($a[#i]!=""){
		$line = $a[#i];
		//$lineに含まれている"lnt.C1."のインデックス
		#ipcIndex = strstr($line, "lnt.C1.");

		if(#ipcIndex != -1){
			//lnt.C1.がある場合は、すぐ右隣に、H01などIPC番号が続く
			//lnt.C1.より右側のIPC番号を含む文字列取得
			//7は、"lnt.C1."の長さ
			#rightlen = strlen($line)-#ipcIndex - 7;
			$ipcNums = rightstr($line, #rightlen);
			//$ipcNums 例）G09F9/30(2006.01)1, GO2F1/1345(2006.01)i 

			//カンマと番号を含むIPC番号の羅列から、IPCだけを取得する
			call GetIPCs $ipcNums;
			$ipcList = $$return;

//			$ipcList ="";
//			while($ipcNums != ""){
//				$ipcNum = leftstr($ipcNums, 1);
//				if($ipcNum != " "){
//					//$ipcNumが取得できたのでIPC番号リストに格納
//					if($ipcList != ""){
//						$ipcList = $ipcList + "," + $ipcNum;
//					}
//					else if($ipcList == ""){
//						$ipcList = $ipcNum;
//					}
//					
//					//次のIPC番号があるか？
//					//カンマもしくは)iで区切られている
//					#commaIndex = strstr($ipcNums, ",");
//					#iIndex = strstr($ipcNums, "i");
//					//カンマも)iもなければ、これ以上IPC番号はない
//					if((#commaIndex == -1) && (#iIndex == -1)){
//						break;
//					}
//
//					//今格納したIPC番号以外を、$ipcNumsに指定
//					if(#commaIndex != -1){
//						//1はカンマ1文字分
//						#rightlen = strlen($ipcNums) - #commaIndex - 1;
//					}
//					else if(#iIndex != -1){
//						#rightlen = strlen($ipcNums) - #iIndex - 1;
//					}
//					
//					$ipcNums = rightstr($ipcNums, #rightlen);
//
//					//test
//					//message "次の$ipcNums = " + $ipcNums;
//					//$ipcNumsが"", " \n", "\n"だったら、break
//					if(($ipcNums == "") || ($ipcNums == " \n") || ($ipcNums == "\n")){
//						//message "break";
//						break;
//					}
//					continue;
//				}
//				//$ipcNumsの先頭に" "があったら省く
//				$ipcNums = rightstr($ipcNums, strlen($ipcNums) - 1);
//			}// end of while



		}//end of if
		else{
			//補充欄参照の場合
			//lnt.C1.がない場合は、例）国際特許分類(I Pc)lnt.C1補充欄参照
			$ipcList = $key30;
			//ファイル名を格納しておく
			//$lineに含まれている"("のインデックス
			#parenIndex = strstr($line, "(");
			$filename = leftstr($line, #parenIndex);
		}//end of else

		//$ipcListを、$ipcNumsList[#k]に格納
		$ipcNumsList[#k] = $ipcList;
		//test
		//message "$ipcNumsList" + str(#k) + "=" + $ipcNumsList[#k];

		#k = #k + 1;

		//クリップボードの次の行を読み込む
		#i = #i + 1;
		$a[#i]=getclipboard;
	}//end of while
	return;


//IPC番号の記載が、補充欄参照の場合、補充欄からIPC番号を取得する
GrepOtherIPCs:

#m = 0;
while (#m != #k){
	$ipcNums = $ipcNumsList[#m];
	if($ipcNums == $key30){
		//補充欄参照の場合、そのファイルを開き、"POT/J"の一行を検索。"1(日.月.年)"の左の文字列が国際出願番号。		
//		message "$filename = " + $filename; //000001_0005.txt
		openfile $filename;
		gofiletop;
		searchdown "POT/J";
		searchdown "1(";
		if(!result){
			break;
		}
		beginsel;
		golinetop;
		copy;
		
		beginclipboardread;
		#i=0;
		$a[#i]=getclipboard;
		//国際出願番号
		$line = $a[#i];
		#pctIndex = strstr($line, "POT/");
		#rightlen = strlen($line)-#pctIndex - 4;
		$iaCode = rightstr($line, #rightlen);
		message "$iaCode = " + $iaCode;

		//取得した国際出願番号でgrepファイル。
		grep $iaCode, "*.txt", ".", regular, fullpath;

		//return;

		//クリップボード履歴を念のため削除
		clearcliphist;
		//grepファイルの内容をコピー
		selectall;
		copy;

		beginclipboardread;
		#i=0;
		$b[#i]=getclipboard;

		//一旦grepした全てのファイルのフルパスを格納
		while($b[#i]!=""){
			#i = #i + 1;
			$b[#i]=getclipboard;
		}//end of while
	
		#i=0;	
		while($b[#i]!=""){
			//$lineは各ファイルのフルパス
			$line = $b[#i];
//			message "$line1 = " + $line;
			//000001_####.txtのファイル（上で$iaCodeを参照したファイル）は既に開いているので、次のファイルに進む。
			if(strstr($line, $filename) != -1){
				#i = #i + 1;
				continue;
			}

			//ここからテスト
			#parenIndex = strstr($line, "(");
			$file = leftstr($line, #parenIndex);

			message "$file = " + $file;

			openfile $file;
			//"補充欄"の文字で始まるファイルの内容を対象に、最終行の"様式POT/I"の検索
			gofiletop;
			searchdown $key31, word;
				
			if(!result){
	//			message "!result, 補充欄なし";
				#i = #i + 1;
				continue;
			}
			//"補充欄"の文字で始まるファイルが見つかった
			//最終行の"様式POT/I"の検索
	//		message "見つかった$file = " + $file;
			gofiletop;
			searchdown "様式POT/I";
			if(result){
				//すぐ上の行に移動
				up;
				selectline;
				searchdown "[ぁ-ン|亜-黑]", regular, inselect;
				if(result){
				    //"様式POT/I"の直前の行に、日本語が含まれていれば、スキップ。
					#i = #i + 1;
					continue;
				}
				//"様式POT/I"の直前の行に、日本語が含まれていなければIPC番号。
				//"の続き"の横からbeginselect. searchdown "様式POT/I" copy して、IPC番号を取得する。
				gofiletop;
				searchdown "の続き";
				down;
				golinetop;
				beginsel;
				searchdown "様式POT/I";
				golinetop;
				copy;

				//IPC番号を取得する
				//取得できない場合は、そのまま補充欄参照とする（後で手入力）
				beginclipboardread;
				$c[0]=getclipboard;
				//IPC番号は１行で羅列してあるので、コピーしたデータの１行目だけ取得でＯＫ
				$ipcTmpNums = $c[0];
				message "$ipcTmpNums =" + $ipcTmpNums;

				//$ipcTmpNumsを整理してIPC番号だけにまとめる。
				//まとめたら、$ipcNumsList[#m]に格納する。
				call GetIPCs $ipcTmpNums;
			    $ipcList = $$return;

				//最後のIPCがCCうまくとれていない。修正する。
				message "$ipcList =" + $ipcList;

				//IPC番号が取得できたのでwhileを出る（次以降のgrepファイル結果は無視）
				break;
			}
			#i = #i + 1;
			

		}//end of while

		
		break;
	}
	#m = #m + 1;
}//end of while

return;

//--------------------------------------
//IPCだけをリストで取得するサブルーチン
//--------------------------------------
GetIPCs:

$ipcList ="";
$ipcNums = $$1;
while($ipcNums != ""){
	$ipcNum = leftstr($ipcNums, 1);
		message "$ipcNum = " + $ipcNum;
	if($ipcNum != " "){
		//$ipcNumが取得できたのでIPC番号リストに格納
		if($ipcList != ""){
			$ipcList = $ipcList + "," + $ipcNum;
		}
		else if($ipcList == ""){
			$ipcList = $ipcNum;
		}
		
		//次のIPC番号があるか？
		//カンマもしくは)iで区切られている
		#commaIndex = strstr($ipcNums, ",");
		#iIndex = strstr($ipcNums, "i");
		//カンマも)iもなければ、これ以上IPC番号はない
		if((#commaIndex == -1) && (#iIndex == -1)){
			break;
		}

		//今格納したIPC番号以外を、$ipcNumsに指定
		if(#commaIndex != -1){
			//1はカンマ1文字分
			#rightlen = strlen($ipcNums) - #commaIndex - 1;
		}
		else if(#iIndex != -1){
			#rightlen = strlen($ipcNums) - #iIndex - 1;
		}
		
		$ipcNums = rightstr($ipcNums, #rightlen);

		//test
		message "ifの中の$ipcNums = " + $ipcNums;
		//$ipcNumsが"", " \n", "\n"だったら、break
		if(($ipcNums == "") || ($ipcNums == " \n") || ($ipcNums == "\n")){
			//message "break";
			break;
		}
		continue;
	}
	//$ipcNumsの先頭に" "があったら省く
	$ipcNums = rightstr($ipcNums, strlen($ipcNums) - 1);
	message "-1した後のの$ipcNums = " + $ipcNums;
}// end of while

return $ipcList;
